paths:
  /create:
    post:
      summary: Create a match
      tags:
        - Match
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMatchRequestBody'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchResponse'
components:
  schemas:
    CreateMatchRequestBody:
      type: object
      properties:
        user_id:
          type: string
          description: The ID of the user.
        winner:
          type: string
          description: The winner of the match.
        opponentName:
          type: string
          description: The name of the opponent. Defaults to "Player 2".
        duration:
          type: number
          description: The duration of the match.
        setsArr:
          type: array
          items:
            $ref: '#/components/schemas/SetRequestBody'
      required:
        - user_id
        - winner
        - duration
        - setsArr

    SetRequestBody:
      type: object
      properties:
        index:
          type: number
          description: The index of the set.
        myScore:
          type: number
          description: The score of the user.
        opponentScore:
          type: number
          description: The score of the opponent.
        myServes:
          type: array
          items:
            type: string
            enum:
              - Ace
              - Winner
              - Forced Error
              - Unforced Error
              - Double Faults
          description: The serves made by the user.
        opponentServes:
          type: array
          items:
            type: string
            enum:
              - Ace
              - Winner
              - Forced Error
              - Unforced Error
              - Double Faults
          description: The serves made by the opponent.

    MatchResponse:
      type: object
      properties:
        _id:
          type: string
          description: The ID of the created match.
        user_id:
          type: string
          description: The ID of the user.
        winner:
          type: string
          description: The winner of the match.
        opponentName:
          type: string
          description: The name of the opponent.
        duration:
          type: number
          description: The duration of the match.
        sets:
          type: array
          items:
            $ref: '#/components/schemas/SetResponse'
          description: The sets of the match.

    SetResponse:
      type: object
      properties:
        _id:
          type: string
          description: The ID of the set.
        index:
          type: number
          description: The index of the set.
        myScore:
          type: number
          description: The score of the user.
        opponentScore:
          type: number
          description: The score of the opponent.
        myServes:
          type: array
          items:
            type: string
            enum:
              - Ace
              - Winner
              - Forced Error
              - Unforced Error
              - Double Faults
          description: The serves made by the user.
        opponentServes:
          type: array
          items:
            type: string
            enum:
              - Ace
              - Winner
              - Forced Error
              - Unforced Error


